In [4]:
import pandas as pd

In [5]:
file_csv = 'indicators.csv'
df = pd.read_csv(file_csv)

In [6]:
df.head()

,Unnamed: 0,Country Name,Indicator Name,Year,Value
0,0,Arab World,"Agriculture, value added (% of GDP)",1952,NaN
1,1,Arab World,CO2 emissions (metric tons per capita),1952,NaN
2,2,Arab World,Domestic credit provided by financial sector (...,1952,NaN
3,3,Arab World,Electric power consumption (kWh per capita),1952,NaN
4,4,Arab World,Energy use (kg of oil equivalent per capita),1952,NaN

In [17]:
df.shape

(85536, 5)

In [23]:
len(countries) * len(indicators) * len(years)

85536

In [21]:
countries = sorted(df["Country Name"].unique())

len(countries), countries

(264,
 ['Afghanistan',
  'Albania',
  'Algeria',
  'American Samoa',
  'Andorra',
  'Angola',
  'Antigua and Barbuda',
  'Arab World',
  'Argentina',
  'Armenia',
  'Aruba',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas, The',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bermuda',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'British Virgin Islands',
  'Brunei Darussalam',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cabo Verde',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Caribbean small states',
  'Cayman Islands',
  'Central African Republic',
  'Central Europe and the Baltics',
  'Chad',
  'Channel Islands',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  'Congo, Dem. Rep.',
  'Congo, Rep.',
  'Costa Rica',
  "Cote d'Ivoire",
  'Croatia',
  'Cuba',
  'Curacao',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Early-demographic dividend',
  'East Asia & Pacific',
  'East Asia & Pacific (IDA & IBRD countries)',
  'East Asia & Pacific (excluding high income)',
  'Ecuador',
  'Egypt, Arab Rep.',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Ethiopia',
  'Euro area',
  'Europe & Central Asia',
  'Europe & Central Asia (IDA & IBRD countries)',
  'Europe & Central Asia (excluding high income)',
  'European Union',
  'Faroe Islands',
  'Fiji',
  'Finland',
  'Fragile and conflict affected situations',
  'France',
  'French Polynesia',
  'Gabon',
  'Gambia, The',
  'Georgia',
  'Germany',
  'Ghana',
  'Gibraltar',
  'Greece',
  'Greenland',
  'Grenada',
  'Guam',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Heavily indebted poor countries (HIPC)',
  'High income',
  'Honduras',
  'Hong Kong SAR, China',
  'Hungary',
  'IBRD only',
  'IDA & IBRD total',
  'IDA blend',
  'IDA only',
  'IDA total',
  'Iceland',
  'India',
  'Indonesia',
  'Iran, Islamic Rep.',
  'Iraq',
  'Ireland',
  'Isle of Man',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Korea, Dem. Peopleï¿½s Rep.',
  'Korea, Rep.',
  'Kosovo',
  'Kuwait',
  'Kyrgyz Republic',
  'Lao PDR',
  'Late-demographic dividend',
  'Latin America & Caribbean',
  'Latin America & Caribbean (excluding high income)',
  'Latin America & the Caribbean (IDA & IBRD countries)',
  'Latvia',
  'Least developed countries: UN classification',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Low & middle income',
  'Low income',
  'Lower middle income',
  'Luxembourg',
  'Macao SAR, China',
  'Macedonia, FYR',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Micronesia, Fed. Sts.',
  'Middle East & North Africa',
  'Middle East & North Africa (IDA & IBRD countries)',
  'Middle East & North Africa (excluding high income)',
  'Middle income',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Caledonia',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'North America',
  'Northern Mariana Islands',
  'Norway',
  'Not classified',
  'OECD members',
  'Oman',
  'Other small states',
  'Pacific island small states',
  'Pakistan',
  'Palau',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Post-demographic dividend',
  'Pre-demographic dividend',
  'Puerto Rico',
  'Qatar',
  'Romania',
  'Russian Federation',
  'Rwanda',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Sint Maarten (Dutch part)',
  'Slovak Republic',
  'Slovenia',
  'Small states',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Asia',
  'South Asia (IDA & IBRD)',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'St. Kitts and Nevis',
  'St. Lucia',
  'St. Martin (French part)',
  'St. Vincent and the Grenadines',
  'Sub-Saharan Africa',
  'Sub-Saharan Africa (IDA & IBRD countries)',
  'Sub-Saharan Africa (excluding high income)',
  'Sudan',
  'Suriname',
  'Swaziland',
  'Sweden',
  'Switzerland',
  'Syrian Arab Republic',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Turks and Caicos Islands',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Upper middle income',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Venezuela, RB',
  'Vietnam',
  'Virgin Islands',
  'West Bank and Gaza',
  'World',
  'Yemen, Rep.',
  'Zambia',
  'Zimbabwe'])

In [20]:
indicators = sorted(df["Indicator Name"].unique())

len(indicators), indicators

(27,
 ['Agriculture, value added (% of GDP)',
  'CO2 emissions (metric tons per capita)',
  'Domestic credit provided by financial sector (% of GDP)',
  'Electric power consumption (kWh per capita)',
  'Energy use (kg of oil equivalent per capita)',
  'Exports of goods and services (% of GDP)',
  'Fertility rate, total (births per woman)',
  'GDP growth (annual %)',
  'GNI per capita, PPP (current international $)',
  'Gross enrollment ratio, primary, both sexes (%)',
  'Gross enrolment ratio, secondary, both sexes (%)',
  'High-technology exports (% of manufactured exports)',
  'Imports of goods and services (% of GDP)',
  'Income share held by lowest 20%',
  'Industry, value added (% of GDP)',
  'Inflation, GDP deflator (annual %)',
  'Internet users (per 100 people)',
  'Life expectancy at birth, total (years)',
  'Military expenditure (% of GDP)',
  'Mobile cellular subscriptions (per 100 people)',
  'Net lending (+) / net borrowing (-) (% of GDP)',
  'Population density (people per sq. km of land area)',
  'Prevalence of HIV, total (% of population ages 15-49)',
  'Revenue, excluding grants (% of GDP)',
  'Services, etc., value added (% of GDP)',
  'Tax revenue (% of GDP)',
  'Time required to start a business (days)'])

In [22]:
years = sorted(df["Year"].unique())

len(years), years

(12, [1952, 1957, 1962, 1967, 1972, 1977, 1982, 1987, 1992, 1997, 2002, 2007])

In [25]:
years[0], years[-1]

(1952, 2007)